#!/usr/bin/env python3
"""Run all production-governance checks and write evidence reports."""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

from check_assets import inspect_assets
from check_claims import check_claims
from check_html_release_safety import check_html_release_safety


def write_asset_manifest(campaign: Path, inventory: list[dict]) -> Path:
    path = campaign / "audit" / "ASSET_MANIFEST.md"
    rows = [
        "# Asset Manifest",
        "",
        "Current asset state: `BLOCKED_ASSET_QA`  ",
        "Generated by deterministic preflight. Human QA status remains required.",
        "",
        "| Asset ID | Filename | File exists? | Intended use | Required format | Actual MIME type | Actual extension | Width | Height | Aspect ratio | Duration if video | Source prompt | Generator | Generated date | Preflight status | Human QA status | Release status | Rejection reason | Notes |",
        "|---|---|---|---|---|---|---|---:|---:|---:|---|---|---|---|---|---|---|---|---|",
    ]
    for index, asset in enumerate(inventory, 1):
        rows.append(
            f"| VJ-ASSET-{index:03d} | `{asset['filename']}` | {asset['exists']} | {asset['intended_use']} | {asset['required_format']} | "
            f"{asset['mime']} | {asset['extension']} | {asset['width'] or 'UNKNOWN'} | {asset['height'] or 'UNKNOWN'} | "
            f"{asset['ratio']} | {asset['duration']} | {asset['source_prompt']} | "
            f"{asset['generator']} | {asset['generated_date']} | {asset['preflight']} | HUMAN_QA_REQUIRED | "
            f"DO_NOT_RELEASE | {asset['reason']} | Existing asset not moved or modified |"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return path


def format_findings(title: str, findings: list[dict]) -> list[str]:
    lines = [f"## {title}", ""]
    if not findings:
        lines.extend(["No issues detected by this deterministic check.", ""])
        return lines
    for item in findings:
        location = item["path"]
        if item.get("line"):
            location += f":{item['line']}"
        lines.append(f"- **{item['severity']} {item['code']}** — `{location}` — {item['message']}")
    lines.append("")
    return lines


def write_reports(campaign: Path, claims: list[dict], assets: list[dict], html: list[dict], inventory: list[dict]) -> tuple[Path, Path]:
    all_findings = claims + assets + html
    counts = Counter(item["severity"] for item in all_findings)
    audit = campaign / "audit"
    audit.mkdir(parents=True, exist_ok=True)
    preflight = audit / "PREFLIGHT_REPORT.md"
    readiness = audit / "RELEASE_READINESS_REPORT.md"
    passed_drafts = sum(
        item["preflight"] == "PREFLIGHT_PASSED" and "/draft/" in f"/{item['filename']}"
        for item in inventory
    )
    missing_video = any(item["exists"] == "NO" and "video" in item["intended_use"].lower() for item in inventory)

    preflight_lines = [
        "# Preflight Report",
        "",
        "**Result: FAIL**" if counts["P0"] else "**Result: PREFLIGHT REVIEW REQUIRED**",
        "",
        f"- Total issues: {len(all_findings)}",
        f"- P0: {counts['P0']}",
        f"- P1: {counts['P1']}",
        f"- P2: {counts['P2']}",
        f"- Claim issues remaining: {len(claims)}",
        f"- Asset issues remaining: {len(assets)}",
        "- Claim cleanup performed: unsupported claim language was evidence-gated." if not claims else "- Claim cleanup performed: further claim remediation is required.",
        "- Asset pipeline remediation created corrected draft stills; human QA and video remain unresolved.",
        "- Promised video deliverable remains unresolved.",
        "- Asset regeneration attempted: YES.",
        f"- New draft stills passing deterministic MIME/dimension/ratio checks: {passed_drafts}.",
        f"- Video status: {'BLOCKED / MISSING' if missing_video else 'REQUIRES DURATION VALIDATION'}.",
        "- Human QA status: HUMAN_QA_REQUIRED for every draft asset.",
        "",
        "A zero-issue deterministic run would not grant human QA or release approval.",
        "",
    ]
    preflight_lines += format_findings("Claims Check", claims)
    preflight_lines += format_findings("Asset MIME, Dimension, Ratio, And Video Check", assets)
    preflight_lines += format_findings("HTML Release-Safety Check", html)
    preflight.write_text("\n".join(preflight_lines) + "\n", encoding="utf-8")

    p0 = [item for item in all_findings if item["severity"] == "P0"]
    readiness_lines = [
        "# Release Readiness Report",
        "",
        "**Current release status: NOT RELEASE READY**",
        "",
        "Reason: P0 blockers remain." if p0 else "Reason: Human QA and approval evidence are still required.",
        "",
        "## Claim Cleanup Status",
        "",
        f"- Remaining claim issues: {len(claims)}",
        "- Unsupported claim language was evidence-gated." if not claims else "- Further claim remediation is required.",
        "- Campaign remains NOT RELEASE READY.",
        "- Corrected draft stills exist; human QA and video issues remain unresolved.",
        "- Promised video deliverable remains unresolved.",
        "- Asset regeneration attempted: YES.",
        f"- Corrected draft stills passing deterministic checks: {passed_drafts}.",
        f"- Video status: {'BLOCKED / MISSING' if missing_video else 'REQUIRES DURATION VALIDATION'}.",
        "- Human QA remains required; no draft asset is approved or release-ready.",
        "",
        "## Blockers",
        "",
    ]
    readiness_lines += [f"- {item['code']}: {item['message']}" for item in p0] or ["- Human QA and required approval evidence remain outstanding."]
    readiness_lines += [
        "",
        "## Required Fixes",
        "",
        "- Verify or remove unsupported claims.",
        "- Preserve legacy invalid assets only as audit history and complete human QA for corrected drafts.",
        "- Supply and validate promised video deliverables.",
        "- Complete and log required human reviews.",
        "",
        "## Next Actions",
        "",
        "1. Resolve P0 blockers using source evidence and corrected deliverables.",
        "2. Re-run deterministic preflight.",
        "3. Complete human QA and approval logs.",
        "4. Keep the campaign out of release until the authorized final launch owner is confirmed by policy.",
    ]
    readiness.write_text("\n".join(readiness_lines) + "\n", encoding="utf-8")
    return preflight, readiness


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python3 scripts/preflight/run_preflight.py <campaign-folder>")
        return 2
    campaign = Path(sys.argv[1]).resolve()
    if not campaign.is_dir():
        print(f"Campaign folder not found: {campaign}")
        return 2

    claim_findings = check_claims(campaign)
    asset_findings, inventory = inspect_assets(campaign)
    html_findings = check_html_release_safety(campaign)
    manifest = write_asset_manifest(campaign, inventory)
    preflight, readiness = write_reports(campaign, claim_findings, asset_findings, html_findings, inventory)
    all_findings = claim_findings + asset_findings + html_findings
    counts = Counter(item["severity"] for item in all_findings)

    print("FAIL" if counts["P0"] else "PREFLIGHT REVIEW REQUIRED")
    print(f"Issue count: {len(all_findings)}")
    print(f"P0: {counts['P0']} | P1: {counts['P1']} | P2: {counts['P2']}")
    print(f"Claim issues: {len(claim_findings)}")
    print(f"Asset issues: {len(asset_findings)}")
    print(f"HTML safety issues: {len(html_findings)}")
    print(f"Asset manifest: {manifest}")
    print(f"Preflight report: {preflight}")
    print(f"Release readiness report: {readiness}")
    print("Recommended next steps: resolve P0 blockers, re-run preflight, then obtain evidence-backed human reviews.")
    return 1 if counts["P0"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
